import { beforeEach,describe,expect,it,mock } from "bun:test"
import { cleanup,render,screen } from "@testing-library/react"

const redirect = mock((path:string) => {throw new Error(`REDIRECT:${path}`)})
const notFound = mock(() => {throw new Error("NOT_FOUND")})
const auth = mock(() => Promise.resolve<{userId:string|null}>({userId:"judge-user"}))
const event = {id:"event-id",name:"Agent Jam",status:"judging",anonymous_judging:false,judging_timezone:"UTC"}
const getPublicHackathon = mock(() => Promise.resolve<unknown>(event))
const getRegistrationInfo = mock(() => Promise.resolve({participantRole:"judge",participantId:"judge-id"}))
const getJudgeAssignments = mock(() => Promise.resolve<unknown[]>([]))
const isJudgingOpenForHackathon = mock(() => Promise.resolve(true))
const listRounds = mock(() => Promise.resolve<Array<{ id: string; status: string; opensAt?: string | null; closesAt?: string | null }>>([]))
const getJudgeDraftTargetIds = mock(() => Promise.resolve<string[]>([]))
let workspace:Record<string,unknown> = {}
mock.module("next/navigation", () => ({redirect,notFound}))
mock.module("@clerk/nextjs/server", () => ({auth}))
mock.module("@/lib/services/public-hackathons", () => ({getPublicHackathon}))
mock.module("@/lib/services/hackathons", () => ({getRegistrationInfo}))
mock.module("@/lib/services/judging", () => ({getJudgeAssignments,isJudgingOpenForHackathon,listRounds}))
mock.module("@/lib/services/judging-reviews", () => ({getJudgeDraftTargetIds}))
mock.module("@/components/hackathon/judging/judge-workspace", () => ({JudgeWorkspace:(props:Record<string,unknown>) => {workspace=props; return <div data-testid="workspace" />}}))
mock.module("@/components/hackathon/judging/judging-inbox", () => ({JudgingInbox:() => <div data-testid="inbox" />}))
mock.module("@/components/page-header", () => ({PageHeader:() => <h1>Judging</h1>}))
mock.module("@/components/ui/auto-refresh", () => ({AutoRefresh:() => null}))
const {default:JudgePage} = await import("@/app/(public)/e/[slug]/judge/page")
const callPage = (review?:string) => JudgePage({params:Promise.resolve({slug:"agent-jam"}),searchParams:Promise.resolve({review})})
const project = {id:"assignment-1",submissionTitle:"One",teamName:"Private team",teamMode:"team",teamMemberCount:3,selfJudging:false,judgingStyle:"weighted_score"}

beforeEach(() => {
  cleanup(); workspace={}; auth.mockResolvedValue({userId:"judge-user"});getPublicHackathon.mockResolvedValue(event)
  getRegistrationInfo.mockResolvedValue({participantRole:"judge",participantId:"judge-id"})
  getJudgeAssignments.mockReset();getJudgeAssignments.mockResolvedValue([])
  getJudgeDraftTargetIds.mockResolvedValue([]);isJudgingOpenForHackathon.mockResolvedValue(true)
  listRounds.mockResolvedValue([])
})
describe("judge workspace page boundary", () => {
  it("requires a signed-in judge before loading assignments or drafts", async () => {
    auth.mockResolvedValueOnce({userId:null})
    await expect(callPage()).rejects.toThrow(`REDIRECT:/sign-in?redirect_url=${encodeURIComponent("/e/agent-jam/judge")}`)
    getRegistrationInfo.mockResolvedValueOnce({participantRole:"participant",participantId:"person"})
    await expect(callPage()).rejects.toThrow("REDIRECT:/e/agent-jam")
    expect(getJudgeAssignments).not.toHaveBeenCalled()
  })
  it("loads private drafts and historical reviews while keeping active assignments separate", async () => {
    getJudgeAssignments.mockResolvedValueOnce([project,{...project,id:"closed-review"}]).mockResolvedValueOnce([project])
    getJudgeDraftTargetIds.mockResolvedValue(["assignment-1"])
    render(await callPage("closed-review"))
    expect(workspace).toMatchObject({activeAssignmentIds:["assignment-1"],draftTargetIds:["assignment-1"],initialReview:"closed-review",canJudge:true,browseEnabled:false})
    expect(getJudgeAssignments).toHaveBeenCalledWith("event-id","judge-user",{includeClosedRounds:true})
    expect(screen.getByTestId("inbox")).toBeDefined()
  })
  it("omits own-team projects before stripping anonymous team fields", async () => {
    getPublicHackathon.mockResolvedValue({...event,anonymous_judging:true})
    getJudgeAssignments.mockResolvedValue([project,{...project,id:"own-project",selfJudging:true}])
    render(await callPage())
    expect(workspace.assignments).toEqual([{...project,teamName:null,teamMode:null,teamMemberCount:null,selfJudging:false}])
    expect(JSON.stringify(workspace.assignments)).not.toContain("Private team")
  })
  it("keeps closed judging history readable and read-only", async () => {
    getPublicHackathon.mockResolvedValue({...event,status:"completed"})
    isJudgingOpenForHackathon.mockResolvedValue(false)
    render(await callPage())
    expect(screen.getByText("Judging is closed")).toBeDefined()
    expect(workspace.canJudge).toBe(false)
    expect(screen.getByTestId("workspace")).toBeDefined()
  })
  it("shows organizer instructions and only enables browsing when configured", async () => {
    getPublicHackathon.mockResolvedValue({...event,judging_instructions:"Please watch each demo.",judging_browse_enabled:true})
    render(await callPage())
    expect(screen.getByText("Please watch each demo.")).toBeDefined()
    expect(workspace.browseEnabled).toBe(true)
  })
  it("shows an invited judge their preparation workspace before judging starts", async () => {
    getPublicHackathon.mockResolvedValue({...event,status:"published"})
    isJudgingOpenForHackathon.mockResolvedValue(false)
    render(await callPage())
    expect(screen.getByText("You're on the judge list")).toBeDefined()
    expect(workspace.canJudge).toBe(false)
  })
  it("closes the header and actionable queue at the configured deadline even if manual status is judging", async () => {
    getPublicHackathon.mockResolvedValue({...event,judging_opens_at:"2000-01-01T12:00:00Z",judging_closes_at:"2000-01-01T14:00:00Z"})
    getJudgeAssignments.mockResolvedValue([project])
    render(await callPage())
    expect(screen.getByText("Judging is closed")).toBeDefined()
    expect(workspace).toMatchObject({canJudge:false,activeAssignmentIds:[]})
    expect(workspace.assignments).toEqual([project])
  })
  it("uses an active round's future schedule for preparation instead of the event schedule", async () => {
    listRounds.mockResolvedValue([{id:"future-round",status:"active",opensAt:"2999-01-01T12:00:00Z",closesAt:"2999-01-01T14:00:00Z"}])
    getJudgeAssignments.mockResolvedValue([{...project,roundId:"future-round"}])
    render(await callPage())
    expect(screen.getByText("Judging opens soon")).toBeDefined()
    expect(workspace).toMatchObject({canJudge:false,activeAssignmentIds:[]})
  })
  it("allows an open round override while leaving expired event-wide reviews read-only", async () => {
    getPublicHackathon.mockResolvedValue({...event,judging_opens_at:"2000-01-01T12:00:00Z",judging_closes_at:"2000-01-01T14:00:00Z"})
    listRounds.mockResolvedValue([{id:"open-round",status:"active",opensAt:"2000-01-01T12:00:00Z",closesAt:"2999-01-01T14:00:00Z"}])
    getJudgeAssignments.mockResolvedValue([project,{...project,id:"round-review",roundId:"open-round"}])
    render(await callPage())
    expect(screen.getByText("Judging is open")).toBeDefined()
    expect(workspace).toMatchObject({canJudge:true,activeAssignmentIds:["round-review"]})
  })
})
