export const ORGANIZER_SECTIONS = [
  "action_items",
  "overview",
  "schedule",
  "challenges",
  "perks",
  "event_page",
  "sponsors",
  "teams",
  "projects",
  "people",
  "judging",
  "judging_setup",
  "judges",
  "rounds",
  "prizes",
  "assignments",
  "results",
  "post_event",
  "fulfillment",
  "feedback",
  "exports",
  "communications",
  "announcements",
  "mentors",
  "social",
  "email",
  "miscs",
  "rooms",
  "activity",
  "terms",
] as const

export type OrganizerSection = (typeof ORGANIZER_SECTIONS)[number]

type OrganizerSectionConfig = {
  title: string
  summary: string
  params: string
  webMcpTools: string[]
  cliCommands: string[]
}

export const ORGANIZER_SECTION_CONFIG: Record<
  OrganizerSection,
  OrganizerSectionConfig
> = {
  action_items: {
    title: "Action items",
    summary: "See the most important work to do next.",
    params: "tab=action-items",
    webMcpTools: ["get_hackathon_overview"],
    cliCommands: ["events get", "events activity"],
  },
  overview: {
    title: "Overview",
    summary: "Review event status, timing, totals, and progress.",
    params: "tab=overview",
    webMcpTools: ["get_hackathon_overview", "set_hackathon_timeline"],
    cliCommands: ["events get", "events update"],
  },
  schedule: {
    title: "Schedule",
    summary: "Review or add event schedule items.",
    params: "tab=overview",
    webMcpTools: ["list_hackathon_schedule", "add_schedule_item"],
    cliCommands: ["schedule list", "schedule add", "schedule update", "schedule delete"],
  },
  challenges: {
    title: "Challenges",
    summary: "Review and add challenges for attendees.",
    params: "tab=challenges",
    webMcpTools: ["list_hackathon_challenges", "add_challenge"],
    cliCommands: ["challenges list", "challenges create", "challenges update", "challenges delete"],
  },
  perks: {
    title: "Perks",
    summary: "Review attendee perks and whether they are released.",
    params: "tab=perks",
    webMcpTools: ["list_hackathon_perks"],
    cliCommands: ["perks list", "perks create", "perks update", "perks release", "perks delete"],
  },
  event_page: {
    title: "Event page",
    summary: "Review and update what people see on the public event page.",
    params: "tab=edit",
    webMcpTools: ["update_hackathon_details"],
    cliCommands: ["events get", "events update"],
  },
  sponsors: {
    title: "Sponsors",
    summary: "Review sponsors shown on the event page.",
    params: "tab=edit",
    webMcpTools: ["list_hackathon_sponsors"],
    cliCommands: ["sponsors list", "sponsors add", "sponsors update", "sponsors remove"],
  },
  teams: {
    title: "Teams",
    summary: "Review team counts, approvals, and team setup.",
    params: "tab=teams",
    webMcpTools: ["get_hackathon_overview"],
    cliCommands: ["teams list", "teams create", "teams approve", "teams deny", "teams update"],
  },
  projects: {
    title: "Projects",
    summary: "Review projects submitted by teams.",
    params: "tab=teams",
    webMcpTools: ["list_hackathon_projects"],
    cliCommands: ["browse submissions"],
  },
  people: {
    title: "People",
    summary: "Review attendee totals and manage event roles.",
    params: "tab=people",
    webMcpTools: ["get_hackathon_overview"],
    cliCommands: [],
  },
  judging: {
    title: "Judging and prizes",
    summary: "Review judging setup, progress, prizes, and results.",
    params: "tab=judging",
    webMcpTools: ["list_hackathon_prizes", "get_hackathon_overview"],
    cliCommands: ["judging judges list", "judging assignments list", "results get"],
  },
  judging_setup: {
    title: "Judging setup",
    summary: "Review what is still needed before judging can start.",
    params: "tab=judging&jtab=setup",
    webMcpTools: ["get_hackathon_overview", "list_hackathon_prizes"],
    cliCommands: ["judging judges list", "judging criteria list"],
  },
  judges: {
    title: "Judges",
    summary: "Review assigned judges and pending invitations.",
    params: "tab=judging&jtab=judges",
    webMcpTools: ["get_hackathon_overview"],
    cliCommands: ["judging judges list", "judging judges add", "judging judges remove"],
  },
  rounds: {
    title: "Rounds",
    summary: "Review judging rounds and who moves on.",
    params: "tab=judging&jtab=rounds",
    webMcpTools: ["get_hackathon_overview"],
    cliCommands: ["tracks list", "tracks create", "tracks update", "tracks activate-round"],
  },
  prizes: {
    title: "Prizes and scoring",
    summary: "Review prizes, scoring rules, and judging progress.",
    params: "tab=judging&jtab=prizes",
    webMcpTools: ["list_hackathon_prizes", "add_prize"],
    cliCommands: ["prizes list", "prizes create", "prizes update", "prizes delete"],
  },
  assignments: {
    title: "Assignments",
    summary: "Review how projects are assigned to judges.",
    params: "tab=judging&jtab=assignments",
    webMcpTools: ["get_hackathon_overview"],
    cliCommands: ["judging assignments list", "judging assignments create", "judging auto-assign"],
  },
  results: {
    title: "Results",
    summary: "Review winners and open the final publishing review.",
    params: "tab=judging&jtab=results",
    webMcpTools: ["open_publish_review", "list_hackathon_prizes"],
    cliCommands: ["results get", "results calculate", "results publish", "results unpublish"],
  },
  post_event: {
    title: "Post-event",
    summary: "Finish prizes, feedback, and event exports.",
    params: "tab=post-event",
    webMcpTools: ["get_hackathon_overview"],
    cliCommands: ["results get"],
  },
  fulfillment: {
    title: "Prize fulfillment",
    summary: "Review prize winners and delivery progress.",
    params: "tab=post-event&ptab=fulfillment",
    webMcpTools: ["list_hackathon_prizes"],
    cliCommands: ["prizes list", "prizes assign", "prizes unassign"],
  },
  feedback: {
    title: "Feedback",
    summary: "Review the feedback survey and send status.",
    params: "tab=post-event&ptab=feedback",
    webMcpTools: ["get_hackathon_overview"],
    cliCommands: [],
  },
  exports: {
    title: "Exports",
    summary: "Open completed-event export tools for human review.",
    params: "tab=post-event&ptab=exports",
    webMcpTools: ["open_hackathon_section"],
    cliCommands: [],
  },
  communications: {
    title: "Communications",
    summary: "Review announcements, mentors, social posts, and email.",
    params: "tab=event",
    webMcpTools: ["list_hackathon_announcements", "draft_announcement"],
    cliCommands: ["announcements list", "announcements create"],
  },
  announcements: {
    title: "Announcements",
    summary: "Review announcements or save a draft for human review.",
    params: "tab=event&etab=announcements",
    webMcpTools: ["list_hackathon_announcements", "draft_announcement"],
    cliCommands: ["announcements list", "announcements create", "announcements publish"],
  },
  mentors: {
    title: "Mentors",
    summary: "Review mentor coverage and the open help queue.",
    params: "tab=event&etab=mentors",
    webMcpTools: ["get_hackathon_overview"],
    cliCommands: [],
  },
  social: {
    title: "Social",
    summary: "Open social post tools for human review.",
    params: "tab=event&etab=social",
    webMcpTools: ["open_hackathon_section"],
    cliCommands: [],
  },
  email: {
    title: "Email",
    summary: "Open event email tools for human review.",
    params: "tab=event&etab=email",
    webMcpTools: ["open_hackathon_section"],
    cliCommands: [],
  },
  miscs: {
    title: "More tools",
    summary: "Review rooms, activity, and event terms.",
    params: "tab=miscs",
    webMcpTools: ["open_hackathon_section"],
    cliCommands: ["events activity", "rooms auto-assign-get"],
  },
  rooms: {
    title: "Rooms",
    summary: "Review room assignments and automatic room setup.",
    params: "tab=miscs&mtab=rooms",
    webMcpTools: ["open_hackathon_section"],
    cliCommands: ["rooms auto-assign-get", "rooms auto-assign-set", "rooms auto-assign-sync"],
  },
  activity: {
    title: "Activity",
    summary: "Review the event activity history.",
    params: "tab=miscs&mtab=activity",
    webMcpTools: ["open_hackathon_section"],
    cliCommands: ["events activity"],
  },
  terms: {
    title: "Terms and conditions",
    summary: "Review attendee terms and acceptance rules.",
    params: "tab=miscs&mtab=terms",
    webMcpTools: ["open_hackathon_section"],
    cliCommands: [],
  },
}
