import { DIRECT_ACTION_TOOL_NAMES } from "@/lib/webmcp/direct-action-tools"

export const ORGANIZER_SECTIONS = [
  "action_items",
  "overview",
  "schedule",
  "challenges",
  "perks",
  "event_page",
  "sponsors",
  "teams",
  "projects",
  "people",
  "judging",
  "judging_setup",
  "judging_settings",
  "judges",
  "rounds",
  "prizes",
  "assignments",
  "results",
  "post_event",
  "fulfillment",
  "feedback",
  "exports",
  "communications",
  "announcements",
  "mentors",
  "social",
  "email",
  "miscs",
  "rooms",
  "activity",
  "terms",
] as const

export type OrganizerSection = (typeof ORGANIZER_SECTIONS)[number]

export const CREATE_EVENT_SURFACE_PARITY = {
  ui: "Create a test event with test data",
  webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "open_test_event_creator"],
  cliCommands: ["events create --test-stage"],
} as const

type OrganizerSectionConfig = {
  title: string
  summary: string
  params: string
  webMcpTools: string[]
  cliCommands: string[]
}

export const ORGANIZER_SECTION_CONFIG: Record<
  OrganizerSection,
  OrganizerSectionConfig
> = {
  action_items: {
    title: "Action items",
    summary: "See, add, finish, reopen, dismiss, or remove organizer tasks.",
    params: "tab=action-items",
    webMcpTools: [
      ...DIRECT_ACTION_TOOL_NAMES,
      "list_organizer_tasks",
      "open_organizer_task",
      "add_organizer_task",
      "complete_organizer_task",
      "reopen_organizer_task",
      "dismiss_organizer_task",
      "remove_organizer_task",
    ],
    cliCommands: [
      "events tasks list",
      "events tasks add",
      "events tasks complete",
      "events tasks reopen",
      "events tasks dismiss",
      "events tasks remove",
    ],
  },
  overview: {
    title: "Overview",
    summary: "Review event status, timing, totals, and progress.",
    params: "tab=overview",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "get_hackathon_overview", "get_hackathon_settings", "update_hackathon_settings", "set_hackathon_timeline", "open_test_event_conversion"],
    cliCommands: ["events get", "events update"],
  },
  schedule: {
    title: "Schedule",
    summary: "Review or add event schedule items.",
    params: "tab=overview",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "list_hackathon_schedule", "inspect_organizer_section", "add_schedule_item"],
    cliCommands: ["schedule list", "schedule add", "schedule update", "schedule delete"],
  },
  challenges: {
    title: "Challenges",
    summary: "Review and add challenges for attendees.",
    params: "tab=challenges",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "list_hackathon_challenges", "inspect_organizer_section", "add_challenge"],
    cliCommands: ["challenges list", "challenges create", "challenges update", "challenges delete"],
  },
  perks: {
    title: "Perks",
    summary: "Review attendee perks and whether they are released.",
    params: "tab=perks",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "list_hackathon_perks", "inspect_organizer_section", "open_hackathon_section"],
    cliCommands: ["perks list", "perks create", "perks update", "perks release", "perks delete"],
  },
  event_page: {
    title: "Event page",
    summary: "Review and update what people see on the public event page.",
    params: "tab=edit",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "get_hackathon_settings", "update_hackathon_settings", "update_hackathon_details"],
    cliCommands: ["events get", "events update"],
  },
  sponsors: {
    title: "Sponsors",
    summary: "Add, edit, or remove sponsors shown on the event page.",
    params: "tab=edit&section=sponsors",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "list_hackathon_sponsors", "get_sponsor_details", "add_sponsor", "update_sponsor", "remove_sponsor", "prepare_sponsor", "inspect_organizer_section", "open_hackathon_section"],
    cliCommands: ["sponsors list", "sponsors add", "sponsors update", "sponsors remove"],
  },
  teams: {
    title: "Teams",
    summary: "Review team setup, approvals, and whether invite emails are sent or queued.",
    params: "tab=teams",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "get_hackathon_overview", "get_hackathon_settings", "update_hackathon_settings", "inspect_organizer_section", "open_hackathon_section"],
    cliCommands: ["teams list", "teams create", "teams approve", "teams deny", "teams update"],
  },
  projects: {
    title: "Projects",
    summary: "Review projects submitted by teams.",
    params: "tab=teams",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "list_hackathon_projects", "inspect_organizer_section", "open_hackathon_section"],
    cliCommands: ["browse submissions"],
  },
  people: {
    title: "People",
    summary: "Review event roles and whether invite emails are sent or queued.",
    params: "tab=people",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "get_hackathon_overview", "inspect_organizer_section", "open_hackathon_section"],
    cliCommands: [],
  },
  judging: {
    title: "Judging and prizes",
    summary: "Review judging setup, progress, prizes, and results.",
    params: "tab=judging",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "inspect_judging", "configure_judging", "open_judging_settings", "list_hackathon_prizes", "get_hackathon_overview", "get_hackathon_settings", "update_hackathon_settings", "inspect_organizer_section", "open_organizer_task", "open_judging_review"],
    cliCommands: ["judging judges list", "judging assignments list", "results get"],
  },
  judging_setup: {
    title: "Judging setup",
    summary: "Review what is still needed before judging can start.",
    params: "tab=judging&jtab=setup",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "inspect_judging", "configure_judging", "open_judging_settings", "get_hackathon_overview", "list_hackathon_prizes", "get_hackathon_settings", "update_hackathon_settings", "inspect_organizer_section", "open_organizer_task", "open_judging_review"],
    cliCommands: ["judging judges list", "judging criteria list"],
  },
  judging_settings: {
    title: "Judging settings",
    summary: "Save prizes first, then finish scorecards, judging dates, rounds, and notifications.",
    params: "tab=judging&jtab=setup",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "inspect_judging", "configure_judging", "save_judging_prize", "save_judging_category", "save_judging_round", "invite_judging_panel", "remind_judging_panel", "inspect_judge_scope", "save_judge_scope", "inspect_judge_projects", "assign_judge_project", "preview_judging_work", "apply_judging_work", "open_judging_settings"],
    cliCommands: ["judging setup inspect", "judging setup configure", "judging scorecards list", "judging judges scope", "judging invitations remind"],
  },
  judges: {
    title: "Judges",
    summary: "Review judges and whether their invite emails are sent or queued.",
    params: "tab=judging&jtab=judges",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "inspect_judging", "invite_judging_panel", "remind_judging_panel", "inspect_judge_scope", "save_judge_scope", "get_hackathon_overview", "inspect_organizer_section", "open_hackathon_section", "open_organizer_task", "open_judging_review"],
    cliCommands: ["judging judges list", "judging judges add", "judging judges remove", "judging judges scope", "judging invitations remind"],
  },
  rounds: {
    title: "Rounds",
    summary: "Review judging rounds and who moves on.",
    params: "tab=judging&jtab=rounds",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "inspect_judging", "save_judging_round", "open_judging_settings", "get_hackathon_overview", "inspect_organizer_section", "open_hackathon_section", "open_organizer_task", "open_judging_review"],
    cliCommands: ["judging rounds list", "judging rounds create", "judging rounds update", "judging rounds activate"],
  },
  prizes: {
    title: "Prizes and scoring",
    summary: "Review prizes, scoring rules, and judging progress.",
    params: "tab=judging&jtab=prizes",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "inspect_judging", "save_judging_prize", "save_judging_category", "list_hackathon_prizes", "inspect_organizer_section", "add_prize", "open_hackathon_section"],
    cliCommands: ["prizes list", "prizes create", "prizes update", "prizes delete"],
  },
  assignments: {
    title: "Assignments",
    summary: "Review how projects are assigned to judges.",
    params: "tab=judging&jtab=assignments",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "inspect_judge_projects", "assign_judge_project", "preview_judging_work", "apply_judging_work", "get_hackathon_overview", "inspect_organizer_section", "open_hackathon_section", "open_organizer_task", "open_judging_review"],
    cliCommands: ["judging assignments list", "judging assignments preview", "judging assignments apply", "judging judges scope", "judging auto-assign"],
  },
  results: {
    title: "Results",
    summary: "Review winners and open the final publishing review.",
    params: "tab=judging&jtab=results",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "open_publish_review", "list_hackathon_prizes", "inspect_organizer_section", "open_judging_review"],
    cliCommands: ["results get", "results calculate", "results publish", "results unpublish"],
  },
  post_event: {
    title: "Post-event",
    summary: "Finish prizes, feedback, and event exports.",
    params: "tab=post-event",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "get_hackathon_overview", "inspect_organizer_section", "open_hackathon_section"],
    cliCommands: ["results get"],
  },
  fulfillment: {
    title: "Prize fulfillment",
    summary: "Review prize winners and delivery progress.",
    params: "tab=post-event&ptab=fulfillment",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "list_hackathon_prizes", "inspect_organizer_section", "open_hackathon_section"],
    cliCommands: ["prizes list", "prizes assign", "prizes unassign"],
  },
  feedback: {
    title: "Feedback",
    summary: "Review the feedback survey and send status.",
    params: "tab=post-event&ptab=feedback",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "get_hackathon_overview", "inspect_organizer_section", "open_hackathon_section"],
    cliCommands: [],
  },
  exports: {
    title: "Exports",
    summary: "Open completed-event export tools for optional review.",
    params: "tab=post-event&ptab=exports",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "inspect_organizer_section", "open_hackathon_section"],
    cliCommands: [],
  },
  communications: {
    title: "Communications",
    summary: "Review announcements, mentors, social posts, and email.",
    params: "tab=event",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "list_hackathon_announcements", "inspect_organizer_section", "draft_announcement", "open_hackathon_section"],
    cliCommands: ["announcements list", "announcements create"],
  },
  announcements: {
    title: "Announcements",
    summary: "Review announcements or save a draft for optional review.",
    params: "tab=event&etab=announcements",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "list_hackathon_announcements", "inspect_organizer_section", "draft_announcement", "open_hackathon_section"],
    cliCommands: ["announcements list", "announcements create", "announcements publish"],
  },
  mentors: {
    title: "Mentors",
    summary: "Review mentor coverage and the open help queue.",
    params: "tab=event&etab=mentors",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "get_hackathon_overview", "inspect_organizer_section", "open_hackathon_section"],
    cliCommands: [],
  },
  social: {
    title: "Social",
    summary: "Open social post tools for optional review.",
    params: "tab=event&etab=social",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "inspect_organizer_section", "open_hackathon_section"],
    cliCommands: [],
  },
  email: {
    title: "Email",
    summary: "Open event email tools for optional review.",
    params: "tab=event&etab=email",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "get_hackathon_settings", "inspect_organizer_section", "open_hackathon_section"],
    cliCommands: [],
  },
  miscs: {
    title: "More tools",
    summary: "Review rooms, activity, and event terms.",
    params: "tab=miscs",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "get_hackathon_settings", "inspect_organizer_section", "open_hackathon_section"],
    cliCommands: ["events activity", "rooms auto-assign-get"],
  },
  rooms: {
    title: "Rooms",
    summary: "Review room assignments and automatic room setup.",
    params: "tab=miscs&mtab=rooms",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "inspect_organizer_section", "open_hackathon_section"],
    cliCommands: ["rooms auto-assign-get", "rooms auto-assign-set", "rooms auto-assign-sync"],
  },
  activity: {
    title: "Activity",
    summary: "Review the event activity history.",
    params: "tab=miscs&mtab=activity",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "get_hackathon_settings", "update_hackathon_settings", "open_hackathon_section"],
    cliCommands: ["events activity"],
  },
  terms: {
    title: "Terms and conditions",
    summary: "Review attendee terms and acceptance rules.",
    params: "tab=miscs&mtab=terms",
    webMcpTools: [...DIRECT_ACTION_TOOL_NAMES, "open_hackathon_section"],
    cliCommands: [],
  },
}
